eduvpn/apple

EduVPN-macOS/Resources/Assets.xcassets/Icon-connected.imageset/Contents.json
EduVPN-macOS/Resources/Assets.xcassets/Icon-connecting.imageset/Contents.json
EduVPN-macOS/Resources/Assets.xcassets/Icon-off.imageset/Contents.json
EduVPN.xcodeproj/project.pbxproj

Minor change affecting macOS only.

Archive fix

---

EduVPN-macOS/Controllers/MainViewController.swift
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Repositories.swift
EduVPN-multiOS/Coordinators/AppCoordinator+ViewControllers.swift
EduVPN-multiOS/Models/CancellablePromise.swift
EduVPN-multiOS/Networking/ApiService.swift
EduVPN-multiOS/Networking/Moya+Promise.swift
EduVPN.xcodeproj/project.pbxproj
EduVPN/ViewControllers/ProvidersViewController.swift

Fixes #121. Also fixes minor build issue with iOS about animated state not being passed along.

Make authorizing with provider cancellable

---

EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift

Fixes #123 by hiding the preference for now.

Hide on demand preference

---

EduVPN-macOS/Config/config-eduvpn.json
EduVPN-macOS/Config/config-eduvpn_dev.json
EduVPN-macOS/Config/config-letsconnect.json
EduVPN-macOS/Controllers/AppDelegate.swift
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Models/Config.swift
EduVPN.xcodeproj/xcshareddata/xcschemes/EduVPN-macOS.xcscheme
EduVPN.xcodeproj/xcshareddata/xcschemes/EduVPNTunnelExtension-macOS.xcscheme

Send user to website for support

---

EduVPN-macOS/Controllers/VPNConnectionViewController.swift
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Models/ServerConfiguration.swift
EduVPN.xcodeproj/project.pbxproj

Show IP addresses

---

EduVPN-multiOS/Models/Managed Objects/Generated/Api+CoreDataProperties.swift
EduVPN-multiOS/Services/FileService.swift
EduVPN.xcodeproj/project.pbxproj
EduVPN.xcodeproj/xcshareddata/xcschemes/EduVPN.xcscheme
EduVPN.xcodeproj/xcshareddata/xcschemes/EduVPNTunnelExtension.xcscheme
EduVPNTests/FileServiceTests.swift

While this change avoids the presence of a double slash in the URL, I am not entirely certain it is bwc.

Avoid double slash in URL

---

EduVPN-multiOS/Models/ProfileModel.swift
EduVPNTests/FileServiceTests.swift

Remove last remnants of Two factor.

---

EduVPN-multiOS/Coordinators/AppCoordinatorError.swift
EduVPN-multiOS/Models/EduVPN.xcdatamodeld/.xccurrentversion
EduVPN-multiOS/Models/EduVPN.xcdatamodeld/EduVPN 8.xcdatamodel/contents
EduVPN-multiOS/Models/Managed Objects/Generated/InstanceGroup+CoreDataProperties.swift
EduVPN-multiOS/Models/Repositories/InstancesRepository.swift
EduVPN.xcodeproj/project.pbxproj

This pull request should fix #147.

Add processing of set value.

---

EduVPN-multiOS/Coordinators/AppCoordinator Delegates/VPNConnectionViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift
EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
EduVPN/ViewControllers/VPNConnectionViewController.swift

Fixes #112 
@johankool Can you implement the Mac bit I marked in this pull request. I will mark the "TODO" with a comment in this pull request.
I still need to test this branch. So please refrain from merging at the moment.

Ask for confirmation when disconnecting.

---

EduVPN-multiOS/Models/Managed Objects/Generated/Api+CoreDataProperties.swift
EduVPN/Models/Crypto.swift

Making Crypto load keys (had to use Application Tag instead of Label, otherwise it wouldn't load keys)
Detecting Secure Enclave availability (attempting to generate EC key pair to detect Secure Enclave)
Making key type, key size, crypto algorithm into instance settings

Updating Crypto to work on devices without Secre Enclave

---

EduVPN.xcodeproj/project.pbxproj

MacOS app was crashing on my machine (MacOS 10.14.6.) due to usage of CryptoKit that is available starting from 10.15.
Implemented solution [found here](https://stackoverflow.com/a/58890638/1602270)

Weak linking for CryptoKit

---

EduVPN/Models/Crypto.swift

@daneagle Can you verify this fix?

Fix Crypto

---

EduVPN/Models/Crypto.swift

Hopefully final fixes to Crypto. I did research on usage of Security framework with and without Secure Enclave. privateKeyUsage setting requires Secure Enclave. Also, to correctly detect presence of Secure Enclave we should use kSecAttrTokenIDSecureEnclave in Crypto initializer, otherwise EC keys may still be successfully generated. However, I'm not sure if EC keys will be usable without Secure Enclave.

Fixes to crypto

---

EduVPN-macOS/Config/Assets-Let’s Connect!.xcassets/secure_access.imageset/Contents.json
EduVPN-macOS/Config/Assets-Let’s Connect!.xcassets/secure_internet.imageset/Contents.json
EduVPN-macOS/Config/Assets-eduVPN.xcassets/secure_access.imageset/Contents.json
EduVPN-macOS/Config/Assets-eduVPN.xcassets/secure_internet.imageset/Contents.json
EduVPN-macOS/Resources/Assets.xcassets/secure_access.imageset/Contents.json
EduVPN-macOS/Resources/Assets.xcassets/secure_internet.imageset/Contents.json
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN.xcodeproj/project.pbxproj

Fix icon colors

---

EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/CustomProviderInputViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/TunnelProviderManagerCoordinatorDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Repositories.swift

Fixes #186 for both Mac and iOS. We need to test error screens throughout the apps.

Make sure to show an error when connect fails

---

CHANGES.md
EduVPN-multiOS/Models/Managed Objects/Generated/Api+CoreDataProperties.swift

Encrypt certificate model as well

---

EduVPN-macOS/Controllers/ProvidersViewController.swift

Row selection should allow adding of provider.

---

EduVPN-multiOS/Coordinators/AppCoordinator.swift
EduVPN-multiOS/Networking/ApiService.swift

When doing institute access... never use a distributed auth flow.

---

EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProvidersViewControllerDelegate.swift

Skip provider type screen if possible

---

EduVPN-macOS/Controllers/EnterProviderURLViewController.swift

Move cursor behind prefilled https://

---

EduVPN-macOS/Controllers/ProvidersViewController.swift

Potential fix for flag mixups

---

EduVPN-macOS/Controllers/VPNConnectionViewController.swift
EduVPN-multiOS/Models/Managed Objects/Profile.swift
EduVPN/ViewControllers/ConnectionsTableViewController.swift
EduVPN/ViewControllers/VPNConnectionViewController.swift

Use localized profile name when available

---

CHANGES.md
EduVPN-macOS/Config/AppVersion-macOS.xcconfig
EduVPN-macOS/Controllers/MainViewController.swift
EduVPN-macOS/Controllers/MainWindowController.swift
EduVPN-macOS/Controllers/ProfilesViewController.swift
EduVPN-macOS/Controllers/ProvidersViewController.swift
EduVPN-macOS/Controllers/VPNConnectionViewController.swift
EduVPN-macOS/Controllers/СonnectionsTableViewController.swift
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ConnectionsTableViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProfilesViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProvidersViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/VPNConnectionViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Repositories.swift
EduVPN-multiOS/Coordinators/AppCoordinator+ViewControllers.swift
EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
EduVPN/Base.lproj/Main.storyboard

Fix for UI not updating properly on macOS

---

CHANGES.md
EduVPN-macOS/Config/config-eduvpn.json
EduVPN-macOS/Config/config-letsconnect.json
EduVPN-macOS/Controllers/AppDelegate.swift
EduVPN-multiOS/Models/Config.swift

Added popup for uninstall instructions older app

---

CHANGES.md
EduVPN-macOS/Controllers/CoreDataFetchedResultsControllerDelegate.swift
EduVPN-macOS/Controllers/ProvidersViewController.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift

Fix UI not updating correctly after removing provider

---

CHANGES.md
EduVPN-macOS/Controllers/VPNConnectionViewController.swift
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/VPNConnectionViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift
EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift

Support for "on demand" preference added

---

CHANGES.md
EduVPN-macOS/Resources/Base.lproj/Main.storyboard
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/VPNConnectionViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
EduVPN/Base.lproj/Main.storyboard

Hide "on demand" setting

---

EduVPN-macOS/Config/AppVersion-macOS.xcconfig

version to 2.1.4

---

EduVPN-macOS/Config/AppVersion-macOS.xcconfig
EduVPN/Config/AppVersion.xcconfig
EduVPN/ViewControllers/SettingsTableViewController.swift

Fix crash on iOS in when opening settings

---

EduVPN-macOS/Config/config-eduvpn.json

uninstall url change

---

CHANGES.md
EduVPN-multiOS/Coordinators/AppCoordinator.swift
EduVPN-multiOS/Services/NotificationsService.swift
EduVPN.xcodeproj/project.pbxproj
EduVPN/AppDelegate.swift
EduVPN/Resources/en.lproj/Localizable.strings
EduVPN/Resources/nl.lproj/Localizable.strings

15 minutes before the certificate actually expires.
Fixes #235

Add back expiry notification

---

.github/workflows/main.yml
CHANGES.md
EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProvidersViewControllerDelegate.swift
EduVPN-multiOS/Coordinators/AppCoordinatorError.swift

Refresh profiles

---

CHANGES.md
EduVPN-multiOS/Coordinators/AppCoordinator+Alert.swift
EduVPN-multiOS/Networking/ApiService.swift
EduVPN/Resources/en.lproj/Localizable.strings
EduVPN/Resources/nl.lproj/Localizable.strings

Display detailed error information on unexpected status code.

---

EduVPN/Resources/Settings.bundle/Acknowledgements.plist
Podfile
Podfile.lock
Pods/Local Podspecs/AppAuth.podspec.json
Pods/Local Podspecs/TunnelKit.podspec.json
Pods/Manifest.lock
Pods/Target Support Files/AppAuth-iOS/AppAuth-iOS-Info.plist
Pods/Target Support Files/AppAuth-macOS/AppAuth-macOS-Info.plist
Pods/Target Support Files/Pods-EduVPN-macOS/Pods-EduVPN-macOS-acknowledgements.markdown
Pods/Target Support Files/Pods-EduVPN-macOS/Pods-EduVPN-macOS-acknowledgements.plist
Pods/Target Support Files/Pods-EduVPN/Pods-EduVPN-acknowledgements.markdown
Pods/Target Support Files/Pods-EduVPN/Pods-EduVPN-acknowledgements.plist
Pods/Target Support Files/Pods-EduVPNTunnelExtension-macOS/Pods-EduVPNTunnelExtension-macOS-acknowledgements.markdown
Pods/Target Support Files/Pods-EduVPNTunnelExtension-macOS/Pods-EduVPNTunnelExtension-macOS-acknowledgements.plist
Pods/Target Support Files/Pods-EduVPNTunnelExtension/Pods-EduVPNTunnelExtension-acknowledgements.markdown
Pods/Target Support Files/Pods-EduVPNTunnelExtension/Pods-EduVPNTunnelExtension-acknowledgements.plist
Pods/Target Support Files/TunnelKit-iOS/TunnelKit-iOS-Info.plist
Pods/Target Support Files/TunnelKit-macOS/TunnelKit-macOS-Info.plist
Pods/TunnelKit/LICENSE
Pods/TunnelKit/README.md
Pods/TunnelKit/TunnelKit/Sources/AppExtension/Transport/NETunnelInterface.swift
Pods/TunnelKit/TunnelKit/Sources/Core/Errors.h
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider+Configuration.swift
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider.swift
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/Configuration.swift
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/OpenVPNSession.swift
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/TLSBox.h
Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/TLSBox.m

Revert back to main development line of TunnelKit.

Change by @roop was merged and improved by @keeshux.

---

CHANGES.md
EduVPN-macOS/Config/Developer-macOS.xcconfig.appforce1-template
EduVPN-macOS/Config/Developer-macOS.xcconfig.eduvpn-template
EduVPN-macOS/Config/Developer-macOS.xcconfig.johan-template
EduVPN-macOS/Config/Developer-macOS.xcconfig.letsconnect-template
EduVPN-macOS/Config/Developer-macOS.xcconfig.template
EduVPN/Config/Developer.xcconfig.appforce1-template
EduVPN/Config/Developer.xcconfig.eduvpn-template
EduVPN/Config/Developer.xcconfig.letsconnect-template
EduVPN/Config/Developer.xcconfig.template
EduVPN/Info.plist

Fixes #301
On simulator iPhone SE (1st gen) iOS 13.5 it looks good. We might want to do some more testing/checking with users with iOS 12 and adjusted font sizes.

Display Let's Connect! as Let's Connect!

---

EduVPN-redesign/AppDelegate.swift
EduVPN-redesign/Resources/Mac/Base.lproj/Main.storyboard
EduVPN-redesign/Shims/NavigationController.swift

Fixes the app menu for the redesigned app.

Fix redesigned app's app menu

---

EduVPN-macOS/Config/config-letsconnect_new_discovery.json
EduVPN/Config/Developer.xcconfig.letsconnect-template
EduVPN/Config/config-letsconnect_new_discovery.json
README.md
Scripts/copy_resources.sh

This PR enables a Let's Connect branding for the redesigned iOS app. Depends on assets from PR #354.
Discovery is temporarily enabled in the Let's Connect app.

Let's Connect redesigned iOS app

---

EduVPN-redesign/Controllers/ConnectionViewController.swift
EduVPN-redesign/Models/DiscoveryData.swift
EduVPN-redesign/Services/ServerAPIService.swift
EduVPN-redesign/ViewModels/ConnectionViewModel.swift
EduVPN-redesign/ViewModels/SearchViewModel.swift

- Fixes 'Renew Session' issues: #341, #349
- Fixes handling of revocation of authorization: #350
- Adds support for keyword_list for Institute Access servers in server_list.json: #343

Some fixes for the redesigned iOS/macOS apps

---

EduVPN-redesign/ViewModels/SearchViewModel.swift

Fix whitespace related issues when pasting a string.

---

EduVPN/Controllers/iOS/MainViewController+iOS.swift

Don't put delete on section headers on iOS.

---

CHANGES.md
EduVPN/Views/MainSecureInternetSectionHeaderCell.swift

iOS: Fix location picker to allow first location as well

---

CHANGES.md
EduVPN/Controllers/ConnectionViewController.swift
EduVPN/Helpers/ConnectionInfoHelper.swift
EduVPN/Models/LanguageMappedString.swift
EduVPN/Models/ServerDisplayInfo.swift
EduVPN/Services/ServerAPIService.swift
EduVPN/ViewModels/ConnectionViewModel.swift
EduVPN/ViewModels/MainViewModel.swift
EduVPN/ViewModels/SearchViewModel.swift

Use strings in discovery data correctly based on system language

---

CHANGES.md
EduVPN/Controllers/MainViewController.swift
EduVPN/Controllers/SearchViewController.swift
EduVPN/Resources/Mac/Base.lproj/Main.storyboard
EduVPN/Resources/iOS/Base.lproj/Main.storyboard
EduVPN/Services/Environment.swift

When the searchVC is shown by direct user action (i.e. by clicking the '+' button or with Cmd+N), the search field is made to get the focus automatically.
Fixes #330.

SearchVC: Auto-focus the search field when applicable

---

EduVPN.xcodeproj/project.pbxproj
EduVPN/AppDelegate.swift
EduVPN/Controllers/ConnectionViewController.swift
EduVPN/Controllers/Mac/MainViewController+StatusItem.swift
EduVPN/Controllers/Mac/StatusItemConnectionInfoHelper.swift
EduVPN/Controllers/Mac/StatusItemController.swift
EduVPN/Controllers/MainViewController.swift
EduVPN/Helpers/ConnectionInfoHelper.swift
EduVPN/Models/ConnectableInstance.swift
EduVPN/Services/Environment.swift
EduVPN/Services/PersistenceService.swift
EduVPN/Shims/NavigationController.swift
EduVPN/ViewModels/ConnectionViewModel+Localization.swift
EduVPN/ViewModels/ConnectionViewModel.swift
EduVPN/ViewModels/MainViewModel.swift

This PR adds status menu items like:
The status menu items are updated through the view controllers because the main window is anyway always created at startup.
Fixes #246.

Show servers in status menu

---

CHANGES.md
EduVPN.xcodeproj/project.pbxproj
EduVPN/Controllers/ConnectionViewController.swift
EduVPN/Controllers/CredentialsViewController.swift
EduVPN/Controllers/Mac/CredentialsViewController+macOS.swift
EduVPN/Controllers/Mac/PasswordEntryViewController.swift
EduVPN/Controllers/iOS/CredentialsViewController+iOS.swift
EduVPN/Controllers/iOS/SettingsViewController.swift
EduVPN/Resources/Mac/Base.lproj/Main.storyboard
EduVPN/Resources/iOS/Base.lproj/Main.storyboard
EduVPN/Services/Environment.swift

This is a follow-up to #380.
Includes:
- macOS: When 'Ask password every time' is selected and the app is asking for password (for an ovpn config instance), make "Return" key connect and "Esc" key disable VPN
- iOS: Support username-password authentication for ovpn config instances

Fix password based ovpn configs handling

---

CHANGES.md
EduVPN/AppDelegate.swift
EduVPN/Controllers/Mac/PreferencesViewController.swift
EduVPN/Controllers/Mac/StatusItemController.swift
EduVPN/Helpers/UserDefaults+Preferences.swift
EduVPN/Resources/Mac/Base.lproj/Main.storyboard

Depends on PR #398 for assets.
In preferences, user can choose whether he wants color icons or grayscale icons. Default is grayscale.

Update status item images

---

CHANGES.md
EduVPN/Networking/DiscoveryDataFetcher.swift
EduVPN/ViewModels/SearchViewModel.swift

Implements rollback prevention https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md#rollback-prevention
Fixes #371.

Discovery data rollback prevention

---

EduVPN/Models/LanguageMappedString.swift
EduVPN/ViewModels/SearchViewModel.swift

Search in discovery data for all languages

---

Config/Mac/config-eduvpn_new_discovery.json
Config/Mac/config-letsconnect_new_discovery.json
Config/iOS/config-eduvpn_new_discovery.json
Config/iOS/config-letsconnect_new_discovery.json
Scripts/update_discovery_resources.pl

As per https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md#signatures

update discovery public keys

---

EduVPN/ViewModels/ConnectionViewModel.swift

Make ConnectionViewModel update its internal state immediately after enabling VPN

---

EduVPN/Networking/ServerAPIv3Handler.swift
EduVPN/Resources/Mac/Base.lproj/Main.storyboard
EduVPN/Resources/iOS/Base.lproj/Main.storyboard

[APIv3](https://github.com/eduvpn/documentation/blob/v2/API_V3.md#connect) offers a new tcp_only parameter on the server, that we can make use of to support this option.

Make "Connect using TCP only" work with APIv3

---

CHANGES.md
EduVPN/AppDelegate.swift
EduVPN/Controllers/ConnectionViewController.swift
EduVPN/Services/NotificationService.swift
EduVPN/ViewModels/ConnectionViewModel.swift

macOS: Show alert on wakeup if session expiry notification was missed

---

EduVPN/AppDelegate.swift

Resolves #431 
When shutting down with the VPN on, don't hold up the shutdown. Rather, silently stop the VPN and quit.
Same applies when restarting and logging out.

macOS: Don't hold up a shutdown / restart when VPN is on

---

CHANGES.md
EduVPN/Controllers/MainViewController.swift
EduVPN/ViewModels/MainViewModel.swift

Update Secure Internet servers from server on app launch

---

LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNProtocol/OpenVPNSession.swift

I'm hoping this will help us figure out from the logs why the tunnel shutdown was initiated. That in turn might help us figure out some issues where the tunnel is seemingly up but no traffic is flowing.

TunnelKit: Add logging when stopping tunnel

---

CHANGES.md
LocalPackages/tunnelkit/Sources/TunnelKitAppExtension/Transport/NETunnelInterface.swift
LocalPackages/tunnelkit/Sources/TunnelKitCore/TunnelInterface.swift
LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNProtocol/OpenVPNSession.swift

Reverting the changes to TunnelKit made trying to fix ENOBUFS errors in #453 because we suspect that might have caused the issue in #481.

Revert ENOBUFS fix

---

CHANGES.md
LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNAppExtension/OpenVPNTunnelProvider.swift
LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNProtocol/OpenVPNSession.swift

Handle sleep-wake cycles correctly
