- CHANGES.md
- EduVPN-multiOS/Coordinators/AppCoordinatorError.swift
- EduVPN-multiOS/Models/EduVPN.xcdatamodeld/.xccurrentversion
- EduVPN-multiOS/Models/EduVPN.xcdatamodeld/EduVPN 9.xcdatamodel/contents
- EduVPN-multiOS/Networking/ApiService.swift
- EduVPN.xcodeproj/project.pbxproj
Fixes #236 
Deleting an InstanceGroup cascades towards all grouped Instances.
So when we cascade across the relation `authorizingForGroup` on an API we delete all grouped configurations when we delete the HOME country.
@johankool What do you think? I will test my assumptions once I have fresh eduROAM credentials.
@efef Do we need to warn the user about the "bigger" deletion the user is about to do?
> Cascade deletion of Api accross `authorizingForGroup` relation.

- CHANGES.md
- EduVPN-macOS/Controllers/ProvidersViewController.swift
- EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProvidersViewControllerDelegate.swift
- EduVPN/ViewControllers/ProvidersViewController.swift
Introduced calculated variable to clarify the meaning of `providerType == .unknown` and applied this check when considering `noProfiles` situations.
> Applied check when considering `noProfiles` situations.

- CHANGES.md
- EduVPN-macOS/Controllers/VPNConnectionViewController.swift
- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
After a disconnect a Connection Info update (updateConnectionInfo in VPNConnectionViewController) would start a new NETunnelProviderSession getting stuck in limbo, which causes an "Extension died unexpectedly" error after a timeout of 20 seconds and preventing a new connect. This fix just empties the Connection Info when disconnecting and returns without calling a new NETunnelProviderSession.
Removing "self.currentManager = NETunnelProviderManager()" prevents a NEVPNStatus of "invalid" and is not necessary anymore with this fix.
> Fix reconnect issue by preventing a new NESMVPNSession stuck in limbo after disconnect

- CHANGES.md
- EduVPN-macOS/Controllers/VPNConnectionViewController.swift
- EduVPN/ViewControllers/VPNConnectionViewController.swift
Like on macOS, this fix prevents a possible reconnect issue on iOS, a new NETunnelProviderSession shouldn't be initialised after a disconnect.
Connection Info should only be updated when in a connected state, a change for macOS in regard to this is included in this commit too.
> iOS: Prevent NETunnelProviderSession initialization after disconnect

- CHANGES.md
- EduVPN-macOS/Controllers/VPNConnectionViewController.swift
- EduVPN-macOS/Resources/Base.lproj/Main.storyboard
- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
- EduVPN/ViewControllers/VPNConnectionViewController.swift
Fixes #247 
- Tunnel log lasts across the last *two* invocations. Done using an option in TunnelKit.
- Tunnel log can be seen even when tunnel is disconnected. Previously, the log was shown as empty unless the tunnel was connected.
- Tunnel log can't be seen when connecting or disconnecting
> Preserve log across tunnel invocations

- EduVPN-macOS/Controllers/VPNConnectionViewController.swift
- EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ConnectionsTableViewControllerDelegate.swift
- EduVPN-multiOS/Coordinators/AppCoordinator+ViewControllers.swift
- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
- EduVPN/ViewControllers/VPNConnectionViewController.swift
Functionality remains unchanged. Line count has slightly *increased* 😞.
Possible follow-ups:
- get rid of `TunnelProviderManagerCoordinator.currentManager`?
- get rid of `UserDefaults.standard.configuredProfileId`?
> Refactor TunnelProviderManagerCoordinator by leveraging PromiseKit

- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
Avoid saving on-demand on an invalid tunnel provider manager
> Fix bug introduced during the refactoring of TunnelProviderManagerCoordinator

- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
Fixes the log having no usable timestamp after PR #274
Looks like we've been setting the wrong log format all along, which TunnelKit was ignoring previously because we weren't using `shouldDebug = true`.
> Remove unrecognized debugLogFormat

- EduVPN-multiOS/Coordinators/AppCoordinator Delegates/CustomProviderInputViewControllerDelegate.swift
- EduVPN-multiOS/Coordinators/AppCoordinator Delegates/ProvidersViewControllerDelegate.swift
- EduVPN-multiOS/Coordinators/AppCoordinator+Repositories.swift
- EduVPN/ViewControllers/CustomProviderInputViewController.swift
There's an assertion failure in macOS when we do either of these:
1. Select a provider, click on _Connect_, authorize, wait
2. Add a custom provider by URL, authorize, wait
Both are related to assert()s in macOS code related to popping view controllers. The failure happens only in debug mode. It won't happen in what we submit to the App Store.
This PR fixes the failure by:
- Removing UI code from `refresh(instance:)` and `connect(url:)`
- Adding UI code for dismissing views after adding a custom provider (iOS)
The assertions themselves are correct, so they are retained.
Tested for the following scenarios in both macOS and iOS: 
- Adding secure internet provider
- Adding institute access provider
- Adding custom provider by URL
- Selecting a provider and connecting
> Fix assertion failure when popping view controllers

- EduVPN/ViewControllers/VPNConnectionViewController.swift
Follow-up to PR #304.
Like showing the spinner on macOS when reasserting, do the same for iOS.
> iOS: Start spinner animation on reasserting too

- EduVPN-multiOS/Coordinators/TunnelProviderManagerCoordinator.swift
Follow-up to PR #304.
Previously, in case the tunnel is down with on-demand set (say the network is down), then the button shows "Disconnect", but wouldn't do anything. This PR fixes that.
> TunnelProviderManagerCoordinator: Disconnect should always disable on-demand

- CHANGES.md
- EduVPN-macOS/Controllers/VPNConnectionViewController.swift
- EduVPN-multiOS/Coordinators/AppCoordinator.swift
- EduVPN-multiOS/Services/NotificationsService.swift
- EduVPN/AppDelegate.swift
- EduVPN/Resources/en.lproj/Localizable.strings
- EduVPN/ViewControllers/VPNConnectionViewController.swift
Addresses #90 
Works so far:
- Notification fires
- Can tap on "Authorize" and have the app refresh the config (to see the action buttons, in macOS, hover on the notification; in iOS, pull down on the notification)
Still to do:
- Add notification strings to localzation strings
- Include minutes remaining in notification (including it is causing the notification to not fire)
- Test the case when the notification is ignored
The notification text reads:
- Title: "Session certificate expiring"
- Text: "Please authorize to continue using the VPN"
- Buttons: "Ignore" / "Authorize"
Any suggestions for better text? (Should be short to fit into the notification.)
> Certificate expiry notification

- EduVPN-redesign/Controllers/PreferencesViewController.swift
- EduVPN-redesign/Helpers/UserDefaults+Preferences.swift
- EduVPN-redesign/Resources/Mac/Base.lproj/Main.storyboard
- EduVPN-redesign/Services/ConnectionService.swift
- EduVPNTunnelExtension-macOS/PacketTunnelProvider.swift
- Pods/TunnelKit/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider.swift
This is intended to fix #311, but it's not clear yet whether it actually fixes it.
This uses NWPathMonitor to figure out when a hasBetterPath change should trigger a reconnection. Since I've not been able to reproduce the reconnection issue well, I've implemented what I think would be a fix, without really being able to verify that it works. So, this PR is made against a new "experimental" branch instead of master. Once merged to "experimental" after review, @efef can build with that and verify the fix.
This PR also exposes an option in the app's Preferences to turn the fix on/off.
> Modify local TunnelKit's handling of hasBetterPath using NWPathMonitor

- EduVPN-redesign/Controllers/MainViewController+macOS.swift
Avoid out-of-bounds array lookup when right-clicking on a 'filler' row, below the valid rows, in the main screen.
Fixes issue #346.
> macOS: MainVC: Fix crash when right-clicking on a 'filler' row

- .github/workflows/main.yml
- EduVPN-UITests-iOS/EduVPNUITestsiOS.swift
- EduVPN-UITests-iOS/TestServerCredentialsiOS.swift-template
- EduVPN-UITests-macOS/EduVPNUITestsmacOS.swift
- EduVPN-UITests-macOS/TestServerCredentialsmacOS.swift-template
- EduVPN.xcodeproj/project.pbxproj
- README.md
This PR does the following:
- Move credentials to a separate file, so that they can be left out of Git versioning
- Allow credential to be nil, which will cause the test using that to be skipped
- Update README
- Bring down deployment target for macOS tests
> Cleanup UI tests

- EduVPN-UITests-iOS/EduVPNUITestsiOS.swift
- EduVPN-UITests-macOS/EduVPNUITestsmacOS.swift
- README.md
- Fix the eduID login mechanism for the 'Demo' server
- The 'Other servers' section header is now hidden when that's the only section, so make the tests not check for that section header
> Fix UI tests

- EduVPN.xcodeproj/project.pbxproj
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Controllers/Mac/PreferencesViewController.swift
- EduVPN/Controllers/MainViewController.swift
- EduVPN/Controllers/iOS/SettingsViewController.swift
- EduVPN/Helpers/CertificateExpiryHelper.swift
- EduVPN/Helpers/UserDefaults+Preferences.swift
- EduVPN/Resources/Mac/Base.lproj/Main.storyboard
- EduVPN/Resources/iOS/Base.lproj/Main.storyboard
- EduVPN/Services/Environment.swift
- EduVPN/Services/NotificationService.swift
- EduVPN/Shims/NavigationController.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
Reintroducing "Your session is about to expire" local notifications in macOS and iOS. 
This was previously implemented in PR #282 but that implementation was removed in the redesigned app. This new implementation introduces a preferences checkbox and a pre-confirmation dialog.
Fixes #90.
> Notify before session expiry

- CHANGES.md
- EduVPN.xcodeproj/project.pbxproj
- EduVPN/EduVPN-macOS-Bridging-Header.h
- EduVPN/Helpers/Mac/OAuthRedirectHTTPHandler.h
- EduVPN/Helpers/Mac/OAuthRedirectHTTPHandler.m
- EduVPN/Services/ServerAuthService.swift
Fixes #182.
We need to override a method in `OIDRedirectHTTPHandler` that's not in its interface, so this PR implements a subclass of `OIDRedirectHTTPHandler` in Objective-C and re-implements that method. This can't be done in Swift because the method we want to override is not part of the interface.
> macOS: Improve HTML page shown after OAuth authentication completes

- EduVPN-Tests-iOS/EduVPNTestsiOS.swift
- EduVPN-UITests-iOS/EduVPNUITestsiOS.swift
- EduVPN-UITests-macOS/EduVPNUITestsmacOS.swift
- EduVPN.xcodeproj/project.pbxproj
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Helpers/CertificateExpiryHelper.swift
- EduVPN/Helpers/Testing.swift
- EduVPN/Models/ConnectionAttempt.swift
- EduVPN/Models/ServerInfo.swift
- EduVPN/Models/ServerResponse.swift
- EduVPN/Networking/ServerAPIv2Handler.swift
- EduVPN/Networking/ServerAPIv3Handler.swift
- EduVPN/Networking/ServerInfoFetcher.swift
- EduVPN/Resources/Mac/Info.plist
- EduVPN/Services/PersistenceService.swift
- EduVPN/Services/ServerAPIService.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
- LoginItemHelper-macOS/Info.plist
- OpenVPNTunnelExtension-macOS/Info.plist
- README.md
- Scripts/build_wireguard_go_bridge.sh
- WireGuardTunnelExtension/PacketTunnelProvider.swift
~~Tested on macOS only. Not tested on iOS yet. Hence in draft.~~
Adds basic support for APIv3 (OpenVPN and WireGuard; iOS and macOS).
No logging or Connection Info yet for WireGuard tunnels.
> Introduce support for eduVPN Server APIv3

- EduVPN/Services/ServerAPIService.swift
Implement forcing of OCSP stapling while using the server API (for #410). (Alamofire implements the revocation stuff, so it was a lot easier than I thought.)
The server API calls work, but I'm not sure if the OCSP stapling is enforced correctly. Maybe we can merge this and then @fkooman can help test it?
> Force OCSP Stapling

- EduVPN/AppDelegate.swift
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Networking/ServerAPIv2Handler.swift
- EduVPN/Networking/ServerAPIv3Handler.swift
- EduVPN/Services/ServerAPIService.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
The macOS app should ensure that "/disconnect" is called and wait a few seconds for it to succeed before quitting.
> macOS: Call "/disconnect" before quitting

- EduVPN.xcodeproj/project.pbxproj
- EduVPN/AppDelegate.swift
- EduVPN/Controllers/AddServerViewController.swift
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Controllers/Mac/AddServerViewController+macOS.swift
- EduVPN/Controllers/Mac/ConnectionViewController+macOS.swift
- EduVPN/Controllers/Mac/MainViewController+macOS.swift
- EduVPN/Controllers/Mac/MenuCommandResponding.swift
- EduVPN/Controllers/Mac/MenuCommandRespondingViewController.swift
- EduVPN/Controllers/Mac/SearchViewController+macOS.swift
- EduVPN/Controllers/MainViewController.swift
- EduVPN/Controllers/SearchViewController.swift
- EduVPN/Resources/Mac/Base.lproj/Main.storyboard
- EduVPN/Shims/NavigationController.swift
- EduVPN/ViewModels/SearchViewModel.swift
Adresses #331.
This PR:
- Disables default keyboard handling in `NSTableView`s in main screen and search screen
- Introduces a 'Server' app menu with menu items for navigating the server list and selecting a server. It also has menu items for selecting profiles and toggling the VPN, but those are applicable only when in the connection screen.
The menus in each screen look like this:
- Main screen:
- Search screen:
- Connection screen: 
Why:
- When in the search screen, we want the search field to have the focus all the time, so that the user can type-to-search anytime. Therefore, we can't have the tableview getting focus and receiving key events. So, we can't make use of the search screen tableview's default keyboard handling.
- The app menu is used for navigating the server list and …
> macOS: Richer app menu to enable keyboard navigation

- CHANGES.md
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Controllers/Mac/StatusItemController.swift
- EduVPN/Networking/Moya/Moya+Promise.swift
- EduVPN/Networking/ServerInfoFetcher.swift
- EduVPN/Services/ServerAPIService.swift
- EduVPN/Services/ServerAuthService.swift
- EduVPN/ViewModels/ConnectionViewModel+Localization.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
This PR fixes #415.
To reproduce the issue reported in #415 in the macOS app:
- Ensure you have added a Secure Internet server in the app. Australia might not be available in the UI. Quit the app.
- Remove the cached server_list.json and organization_list.json by deleting everything under ~/Library/Containers/<bundle_id>/Data/Library/Caches/DiscoveryData
- Turn off wifi / ethernet on your Mac. Open the app. The server_list.json and organization_list.json bundled with the app still have Australia as a Secure Internet location, so when we open the app, we can now see Australia in the UI. Select Australia as the Secure Internet location.
- Turn on wifi / ethernet. Click on the Australia list item to start the connection flow. The connection screen is pushed in, saying "Getting Profiles...", …
> Make fetching info.json cancellable

- CHANGES.md
- EduVPN/ViewModels/SearchViewModel.swift
Fixes #407.
- If the scheme is 'http', change that to 'https'.
- If the scheme is neither 'http' nor 'https', don't consider it to be a custom server URL.
- If the scheme is 'https', consider that to be valid as is.
> Search UX: Handle wrong scheme in custom server URLs

- EduVPN/Services/ServerAPIService.swift
This PR removes the code for OCSP stapling (that wasn't fully working) added in PR #411.
I can see that OCSP stapling is enforced (i.e. app doesn't connect if there's no
stapled OCSP response in the TLS handshake) if we use the following options:
- kSecRevocationOCSPMethod
- kSecRevocationRequirePositiveResponse
- kSecRevocationNetworkAccessDisabled
But some eduVPN servers (e.g. Secure Internet servers of Finland and
France) have OCSP stapling disabled, so we don't want to enforce OCSP
stapling at present.
> Remove enforcing of OCSP stapling

- CHANGES.md
- EduVPN/Helpers/CertificateExpiryHelper.swift
- EduVPN/Models/ConnectionAttempt.swift
- EduVPN/Networking/ServerAPIv2Handler.swift
- EduVPN/Networking/ServerAPIv3Handler.swift
- EduVPN/Services/NotificationService.swift
- EduVPN/Services/PersistenceService.swift
- EduVPN/Services/ServerAPIService.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
Whenever the app successfully performs an OAuth authorization using a browser, the app shall note down that time as the authorization time. The renew button and the session-about-expire notification shall be suppressed 32 mins from that time (because the browser session shall be active for 30 mins -- the 2 mins is a buffer).
> Suppress renewal when the browser session is active from authentication

- CHANGES.md
- EduVPN/Helpers/SignatureHelper.swift
Fixes #427. Tested with pre-hashed and legacy signatures generated with minisign 0.10.
- To disable legacy signature in the future, should set `SignatureHelper.isLegacySignatureAllowed` to `false`
- Apple's CryptoKit doesn't have Blake2s hashing, so we use Blake2s from libsodium. Consequently, we now use libsodium even for latest iOS / macOS.
- The publicKey can still have the signature algorithm id as "Ed" (legacy) instead of "ED" (pre-hashed), so we don't compare the publicKey's signature algorithm id with the signature's signature algorithm id.
> Add support for prehashed minisign signatures

- EduVPN/Controllers/Mac/StatusItemController.swift
- EduVPN/Helpers/CertificateExpiryHelper.swift
Fixes #436.
When setting a grayscale status item image, we should be using the image in template mode.
> macOS: Fix status bar icon

- .github/workflows/main.yml
This PR fixes our GitHub Actions setup as follows:
- Uses checkout@v2 (fixes #433)
- Uses a simpler changelog check, which doesn't require a GitHub token
- Makes the project build again on CI
- Uses [maxim-lobanov/setup-xcode](https://github.com/maxim-lobanov/setup-xcode) so we don't have to manually keep the Xcode version up-to-date in our GitHub Actions setup
> Fix GitHub Actions

- EduVPN/Networking/ServerAPIv3Handler.swift
The profile_id parameter to "/disconnect" is no longer required as per https://github.com/eduvpn/documentation/commit/ba0eea91c41344e81dc6f8de06511c6826a100dc
> APIv3: Don't pass profile_id to disconnect

- CHANGES.md
- EduVPN.xcodeproj/project.pbxproj
- EduVPN/Helpers/CertificateExpiryHelper.swift
- EduVPN/Helpers/SessionExpiryHelper.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
Resolves #430.
The main part of fixing #430 was inadvertently merged as part of PR #437 (in commit 19c8154).
This PR finishes that up by making sure the "Renew Session" button is correctly shown/hidden when the device wakes up after sleep while the VPN is on.
> Fix certificate expiry helper

- CHANGES.md
- EduVPN/AppDelegate.swift
- EduVPN/Controllers/ConnectionViewController.swift
- EduVPN/Controllers/Mac/PreferencesViewController.swift
- EduVPN/Controllers/MainViewController.swift
- EduVPN/Controllers/iOS/SettingsViewController.swift
- EduVPN/Resources/Mac/Base.lproj/Main.storyboard
- EduVPN/Resources/iOS/Base.lproj/Main.storyboard
- EduVPN/Services/NotificationService.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
This PR does the following:
1. Show notification when session has expired
2. If the app is in the foreground when (a) session is about to expire in 30 mins, or (b) session expires, or (c) when device wakes up and (a) or (b) is true, we show an alert instead of a notification
3. Since (2) above can result in multiple alerts, we keep track of whether a previous session-expiry-related alert is being shown or not. We show an alert only if another is not already being shown undismissed.
Fixes #442 and #445.
> Improve session expiry notifications

- CHANGES.md
- EduVPN/Networking/ServerAPIv3Handler.swift
- Use prefer_tcp instead of tcp_only
- Change accept header for `/connect` from `application/json` to `application/x-openvpn-profile, application/x-wireguard-profile`
> Fix usage of API v3

- EduVPN/Helpers/Mac/OAuthRedirectHTTPHandler.m
Noticed a typo in the string that is displayed after you've pressed 'authorize' in your web browser.
> Fix typo in oauth confirmation msgbox

- CHANGES.md
- EduVPN/Controllers/Mac/PreferencesViewController.swift
- EduVPN/Controllers/iOS/SettingsViewController.swift
- EduVPN/Resources/Mac/Base.lproj/Main.storyboard
- EduVPN/Resources/iOS/Base.lproj/Main.storyboard
- EduVPN/Shims/NavigationController.swift
This PR adds access to the privacy statement from Settings (in the iOS app) / Preferences (in the macOS app).
Before this PR, once the user accepts the privacy statement, there's no way for her to read the statement again. This PR attempts to solve for that use case.
> Access privacy statement from settings

- CHANGES.md
- EduVPN/Resources/iOS/Assets-eduVPN.xcassets/TopBarLogo.imageset/Contents.json
- EduVPN/Resources/iOS/Common.xcassets/QuestionButton.imageset/Contents.json
- EduVPN/Resources/iOS/Common.xcassets/SectionHeaderInstituteAccess.imageset/Contents.json
- EduVPN/Resources/iOS/Common.xcassets/SectionHeaderOwnServer.imageset/Contents.json
- EduVPN/Resources/iOS/Common.xcassets/SectionHeaderSecureInternet.imageset/Contents.json
- EduVPN/Resources/iOS/Common.xcassets/SettingsButton.imageset/Contents.json
- EduVPN/Shims/NavigationController.swift
This PR fixes issues found on the iPad:
- Fixes crash when showing the Privacy Statement (uses alert style now)
- Makes Settings and Help buttons visible
- Makes section header images in the main view visible
> Ensure app works on the iPad

- CHANGES.md
- EduVPN/Controllers/Mac/StatusItemConnectionInfoHelper.swift
- EduVPN/Helpers/ConnectionInfoHelper.swift
- EduVPN/Services/ConnectionService.swift
- EduVPN/Services/MockConnectionService.swift
- EduVPN/ViewModels/ConnectionViewModel.swift
- OpenVPNTunnelExtension/PacketTunnelProvider.swift
- Shared/Shared.swift
- WireGuardTunnelExtension/PacketTunnelProvider.swift
Resolves #319
Previously, we got the connected date in the app by looking at `NEVPNConnection.connectedDate`. That value didn't get updated across sleep-wakeups (when the OpenVPN tunnel might get disconnected / reconnected which would reset the data counters). So in this PR, we get the connected date by querying the tunnel extension.
> Fix connected time being incorrect

- CHANGES.md
- EduVPN/Controllers/MainViewController.swift
- EduVPN/Controllers/SearchViewController.swift
- EduVPN/Services/PersistenceService.swift
- EduVPN/Shims/Multiplatform.swift
This PR fixes a couple of bugs in master that would show up only in the eduVPN app
1. When adding / removing a server when a secure internet server exists, the app crashes because of the way UITableView handles reloads. (iOS only)
2. When the last server deleted is a secure internet server, the app doesn't automatically go back to the search screen. (iOS and macOS)
> eduVPN bugfixes

- LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNAppExtension/OpenVPNTunnelProvider.swift
This PR tries to add logging to the tunnel log so that we can detect and figure out a fix for #311, in case we ever see it again.
(Not updating changelog because this is a logging only PR)
> TunnelKit: Setup a path monitor to verify validity of socketHasBetterPath calls

- CHANGES.md
- EduVPN/Controllers/MainViewController.swift
Attempts to fix #469 
I can't reproduce the reported problem, but the reported problem looks very similar to https://github.com/openid/AppAuth-iOS/issues/498, so I think this PR should fix it. We can merge this and have @efef check if the issue is solved or not.
> Postpone renew session until the app is in the foreground

- CHANGES.md
- LocalPackages/tunnelkit/Sources/TunnelKitAppExtension/Transport/NETunnelInterface.swift
- LocalPackages/tunnelkit/Sources/TunnelKitCore/TunnelInterface.swift
- LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNProtocol/OpenVPNSession.swift
Fixes #481.
When sending data packets, the encryption currently happens in the NEPacketTunnelFlow's queue. The OpenVPN ping packets are sent from the OpenVPNSession object's queue. This results in encryptions happening in parallel, especially when sending lots of packets in a short time. Since both kinds of packets use the same crypto context, this results in the same crypto context being accessed from two different threads at the same time.
Consider the code for [encryptBytes](https://github.com/eduvpn/apple/blob/master/LocalPackages/tunnelkit/Sources/CTunnelKitOpenVPNProtocol/CryptoAEAD.m#L123). If two threads are simultaneously executing that method, and both thread have finished EVP_CipherInit, then after one thread exits EVP_CipherFinal_ex, the other thread's EVP_CipherFinal_ex call …
> TunnelKit: Queue the data packets to avoid crypto errors

- CHANGES.md
- LocalPackages/tunnelkit/Sources/TunnelKitOpenVPNAppExtension/OpenVPNTunnelProvider.swift
Fixes #485.
When the tunnel is not in a position to work anymore, cancel the tunnel (i.e. tell the OS to dismantle the tunnel). Then the tunnel process shall exit and the on-demand shall make the OS launch the tunnel afresh when required. If we don't do this, the tunnel sometimes gets to a state where the tunnel process is alive but is not handing any packets.
> Fix no-internet issues in OpenVPN

- CHANGES.md
- EduVPN/Controllers/iOS/LogViewController.swift
- EduVPN/Resources/iOS/Base.lproj/Main.storyboard
It's hard to browse the log on iOS, so this PR adds a "Copy Log" button in the nav bar, so that the log can be copied out of the app (and pasted into an email or a webpage).
It looks like this:
https://user-images.githubusercontent.com/554/204038537-41970fd8-d64f-41f2-9bda-a2f7cefa0014.MP4
> iOS: Add 'Copy Log' button

- CHANGES.md
- EduVPN/Controllers/MainViewController.swift
It looks like viewDidAppear never gets called when we launch into the main VC, so we should look for the viewDidLoad call as well.
Probably fixes #503.
> iOS: Fix UI updating when deleting a server

- CHANGES.md
- EduVPN/AppDelegate.swift
- EduVPN/Controllers/Mac/StatusItemController.swift
Fixes #497.
We need to activate the app when showing the About panel.
> Fix showing About panel from status item menu

- CHANGES.md
- EduVPN.xcodeproj/project.pbxproj
- EduVPN.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OpenVPNTunnelExtension/PacketTunnelProvider.swift
Fixes #493.
iOS seems to keep sending the tunnel sleep / wake notifications while the device is locked (could be for background network access). So in this PR, we don't do anything on these notifications for iOS (and continue to pause / resume the tunnel in macOS), and just let the OS manage the tunnel as it sees fit (because on-demand is still on).
> Suppress sleep wake handling in ios

- CHANGES.md
- EduVPN.xcodeproj/project.pbxproj
- EduVPN.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OpenVPNTunnelExtension/PacketTunnelProvider.swift
Fixes #494.
When the tunnel is on, and the authorisation is revoked on the server, then the OpenVPN tunnel will error out and try to reconnect. Because of on-demand, the OS keeps trying to turn the tunnel on, and the client keeps contacting the server again and again.
To prevent this, in this PR, when the tunnel is turned on by the OS, if the tunnel sees an unrecoverable AUTH_FAIL, it shuts down the tunnel but keeps the tunnel process alive. It also tries to show a message to the user with a deprecated API (displayMessage()), which seems to work on macOS but not on iOS. To the user, the tunnel will be in "Connecting ..." state.
> Suppress retry on auth failure

- CHANGES.md
- EduVPN/Models/AuthState.swift
- EduVPN/Services/ServerAPIService.swift
Fixes #487.
In moving from APIv2 to APIv3, the server endpoints changed. After that, when the client connects to the server, it resulted in an error because the client was using a cached OIDAuthState object, which included the endpoints used -- when refreshing the token, AppAuth used the endpoints stored in the OIDAuthState, instead of the provided endpoints.
In this PR, we check if the endpoints stored in the OIDAuthState are the same as the ones we want to contact. AppAuth exposes the endpoints stored in the AuthState, so we are able to check it without having to modify AppAuth.
> Do not use AuthState with non-matching endpoints

- CHANGES.md
- EduVPN/Networking/ServerAPIv2Handler.swift
- EduVPN/Networking/ServerAPIv3Handler.swift
Fixes #489.
All errors from accessing the server API (APIv3), or on parsing the data got from the server API (including JSON parsing errors), show the server URL.
@fkooman Some examples:
"/info" errors out:
"/connect" errors out:
Error parsing returned JSON:
Only the most used APIv2 stuff is updated -- the rest of APIv2's error messaging is left unimproved.
> Better error messages

- .github/workflows/main.yml
- CHANGES.md
- EduVPN.xcodeproj/project.pbxproj
- EduVPN.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update WireGuardKit to include the fix for a fatal error in Swift.
> Update WireGuardKit to fix Swift fatal error in tunnel extension
